pessoa:
  p001 : "Isabela"
  p002 : "Nathalia"
  p003 : "Thyago"

camera:
  flir: "c001"
  vue: "c002"
  canon_front: "c003"
  canon_side: "c004"
  
paths:
  flir: 'E:/flir/reconhecimento'
  vue: 'E:/vue/reconhecimento'
  canon_front: 'E:/canon_front/reconhecimento'
  canon_side: 'E:/canon_side/reconhecimento'
