pessoa:
  p001 : "Isabela"
  p002 : "Nathalia"
  p003 : "Thyago"

camera:
  flir: "c001"
  vue: "c002"
  canon: "c003"
paths:
  flir: 'E:/flir/reconhecimento'
  vue: 'E:/vue/reconhecimento'
  canon: 'E:/canon/reconhecimento'
