pessoa:
  p001 : "Isabela"
  p002 : "Nathalia"
  p003 : "Thyago"

camera:
  flir: "c001"
  vue: "c002"
  canon_front: "c003"
  canon_side: "c004"
  
paths:
  flir: '/mnt/data/anamnese/raw/flir'
  vue: '/mnt/data/anamnese/raw/vue'
  canon_front: '/mnt/data/anamnese/raw/canon_front'
  canon_side: '/mnt/data/anamnese/raw/canon_side'